### ISSUE TITLE
pattern.test is not a function

### ISSUE THREAD

**Issue by mpuz** [ndaidong/article-parser#301]
I have an error "pattern.test" is not a function.. when I edit file transformations.js and replace test with match (pattern.match(url))- error is gone but transformation does not work
url - https://www.coindesk.com/business/2022/09/18/institutions-are-still-wait-and-see-with-ethereum/
```
TypeError: pattern.test is not a function
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/article-parser/src/utils/transformation.js:51:75
    at Array.some (<anonymous>)
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/article-parser/src/utils/transformation.js:51:49
    at Array.some (<anonymous>)
    at findTransformations (file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/article-parser/src/utils/transformation.js:51:26)
    at execPreParser (file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/article-parser/src/utils/transformation.js:61:3)
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/article-parser/src/utils/parseFromHtml.js:83:14
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/bellajs/src/utils/pipe.js:4:38
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/bellajs/src/utils/pipe.js:4:40
    at file:///home/user/Dropbox/PROJECTS/.../backend/node_modules/bellajs/src/utils/pipe.js:4:40 ```

**Comment by mpuz** [comment]
pattern: 
```
patterns: [
        '*://*.coindesk.com/*'
    ],
```

**Comment by mpuz** [comment]
well, this was my own mistake - i provided string instead of regex into pattern!
